// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFilterPreset(arg1) {
  return window['go']['main']['App']['DeleteFilterPreset'](arg1);
}

export function ExportAtendimentosExcel(arg1) {
  return window['go']['main']['App']['ExportAtendimentosExcel'](arg1);
}

export function ExportAtendimentosPDF(arg1) {
  return window['go']['main']['App']['ExportAtendimentosPDF'](arg1);
}

export function GetAcoes() {
  return window['go']['main']['App']['GetAcoes']();
}

export function GetAnalistas() {
  return window['go']['main']['App']['GetAnalistas']();
}

export function GetAtendimentos(arg1) {
  return window['go']['main']['App']['GetAtendimentos'](arg1);
}

export function GetCategorias() {
  return window['go']['main']['App']['GetCategorias']();
}

export function GetFilterPresets() {
  return window['go']['main']['App']['GetFilterPresets']();
}

export function GetHistoricos(arg1) {
  return window['go']['main']['App']['GetHistoricos'](arg1);
}

export function GetSetores() {
  return window['go']['main']['App']['GetSetores']();
}

export function GetSistemas() {
  return window['go']['main']['App']['GetSistemas']();
}

export function GetUnidades() {
  return window['go']['main']['App']['GetUnidades']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsDatabaseConfigured() {
  return window['go']['main']['App']['IsDatabaseConfigured']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function SaveDatabaseConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveDatabaseConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFilterPreset(arg1, arg2) {
  return window['go']['main']['App']['SaveFilterPreset'](arg1, arg2);
}

export function SearchClientes(arg1) {
  return window['go']['main']['App']['SearchClientes'](arg1);
}

export function TestDatabaseConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestDatabaseConfig'](arg1, arg2, arg3, arg4, arg5);
}
