// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {repository} from '../models';

export function DeleteFilterPreset(arg1:string):Promise<void>;

export function ExportAtendimentosExcel(arg1:models.AtendimentoFilter):Promise<string>;

export function ExportAtendimentosPDF(arg1:models.AtendimentoFilter):Promise<string>;

export function GetAcoes():Promise<Array<models.LookupOption>>;

export function GetAnalistas():Promise<Array<models.LookupOption>>;

export function GetAtendimentos(arg1:models.AtendimentoFilter):Promise<Array<models.Atendimento>>;

export function GetCategorias():Promise<Array<models.LookupOption>>;

export function GetFilterPresets():Promise<Array<repository.FilterPreset>>;

export function GetHistoricos(arg1:number):Promise<Array<models.HistoricoAtendimento>>;

export function GetSetores():Promise<Array<models.LookupOption>>;

export function GetSistemas():Promise<Array<models.LookupOption>>;

export function GetUnidades():Promise<Array<models.LookupOption>>;

export function Greet(arg1:string):Promise<string>;

export function IsDatabaseConfigured():Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function SaveDatabaseConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function SaveFilterPreset(arg1:string,arg2:models.AtendimentoFilter):Promise<void>;

export function SearchClientes(arg1:string):Promise<Array<models.LookupOption>>;

export function TestDatabaseConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;
